<a href="https://colab.research.google.com/github/fjrzhn098-droid/Projekcoding/blob/master/LatihanDAAM03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from datetime import date
tgl_v1 = date.today()
print(tgl_v1)

import datetime as vDate
hari = vDate.date.day

tanggal = vDate.date.today()
print(hari)
print(tanggal)

mahasiswa = ["Fajar", "2024071028","informatika","DAA", tanggal, "Universitas Pembangunan Jaya"]
print(mahasiswa)

2025-09-15
<attribute 'day' of 'datetime.date' objects>
2025-09-15
['Fajar', '2024071028', 'informatika', 'DAA', datetime.date(2025, 9, 15), 'Universitas Pembangunan Jaya']


In [ ]:
print("NIM ", mahasiswa[1])
print("kampus ", mahasiswa[5])


NIM  2024071028
kampus  Universitas Pembangunan Jaya


In [ ]:
#nim saja
print("NIM ", mahasiswa[1:2])

NIM  ['2024071028']


In [ ]:
#prodi saja
print("prodi ", mahasiswa[2:3])

prodi  ['informatika']


In [ ]:
#nim dan prodi
print("NIM & Prodi ", mahasiswa[1:3])

NIM & Prodi  ['2024071028', 'informatika']


In [ ]:
#MK dan tanggal
print("MK dan tanggal ", mahasiswa[3:5])

MK dan tanggal  ['DAA', datetime.date(2025, 9, 15)]


In [1]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
print("Tuple UPJ:", UPJ)

Tuple UPJ: ('Universitas', 'Pembangunan', 'Jaya')


In [2]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))
print("Nested Tuple:", nested_tuple)

Nested Tuple: (100, (200, 400, 600), 300, (400, 800))


In [3]:
mhs_dict = {
    "Nama": "Fajar",
    "NIM": "2024071028",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print("Dictionary:", mhs_dict)

Dictionary: {'Nama': 'Fajar', 'NIM': '2024071028', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [4]:
print("Nama:", mhs_dict["Nama"])
print("Prodi:", mhs_dict["Prodi"])

Nama: Fajar
Prodi: Informatika


In [5]:
warna = {"red", "green", "blue", "red"}
print("Set warna:", warna)

Set warna: {'green', 'red', 'blue'}


In [6]:
import pandas as pd
data = {
    "No": [1, 2, 3],
    "Prodi": ["Informatika", "Sistem Informasi", "Teknik Sipil"],
    "Mahasiswa": [50, 55, 40],
    "Laki-laki": [30, 30, 30],
    "Perempuan": [20, 25, 10]
}
mhs = pd.DataFrame(data)
print(mhs)


   No             Prodi  Mahasiswa  Laki-laki  Perempuan
0   1       Informatika         50         30         20
1   2  Sistem Informasi         55         30         25
2   3      Teknik Sipil         40         30         10


In [7]:
import numpy as np

matriks = np.array([[100, 200, 300],
                    [700, 600, 500],
                    [900, 1000, 800]])
print("Matrix:\n", matriks)

Matrix:
 [[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
